// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  window.Gun = (function(_super) {

    __extends(Gun, _super);

    Gun.name = 'Gun';

    Gun.prototype.size = 3;

    Gun.prototype.bounds = 100;

    Gun.prototype.buffer = 12;

    Gun.create = function() {
      return {
        top: new Gun('top'),
        right: new Gun('right'),
        bottom: new Gun('bottom'),
        left: new Gun('left')
      };
    };

    function Gun(type) {
      this.type = type;
      Gun.__super__.constructor.call(this, new THREE.CubeGeometry(this.size, this.size, this.size), new THREE.MeshPhongMaterial({
        color: 0x0000ff
      }));
      this.horizontal = this.type === 'top' || this.type === 'bottom';
      this.vertical = !this.horizontal;
      if (this.type === 'top') {
        this.position.y = 100 + this.buffer;
      }
      if (this.type === 'right') {
        this.position.x = 100 + this.buffer;
      }
      if (this.type === 'bottom') {
        this.position.y = -100 - this.buffer;
      }
      if (this.type === 'left') {
        this.position.x = -100 - this.buffer;
      }
      if (this.horizontal) {
        this.scale.y = 5;
      }
      if (this.vertical) {
        this.scale.x = 5;
      }
    }

    Gun.prototype.updatePosition = function(pos) {
      if (this.horizontal) {
        this.position.x = pos.x;
        if (this.position.x > this.bounds) {
          this.position.x = this.bounds;
        }
        if (this.position.x < -this.bounds) {
          this.position.x = -this.bounds;
        }
      }
      if (this.vertical) {
        if (this.vertical) {
          this.position.y = pos.y;
        }
        if (this.position.y > this.bounds) {
          this.position.y = this.bounds;
        }
        if (this.position.y < -this.bounds) {
          return this.position.y = -this.bounds;
        }
      }
    };

    return Gun;

  })(THREE.Mesh);

}).call(this);
