// Generated by CoffeeScript 1.3.1
(function() {

  window.Stage = (function() {

    Stage.name = 'Stage';

    function Stage() {
      var gun, type, _ref,
        _this = this;
      this.mesh = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshNormalMaterial());
      scene.add(this.mesh);
      this.crosshair = new Crosshair;
      this.mesh.add(this.crosshair);
      this.guns = Gun.create();
      _ref = this.guns;
      for (type in _ref) {
        gun = _ref[type];
        this.mesh.add(gun);
      }
      $(document.body).on('mousemove', function(e) {
        var gun, pointerPos, type, _ref1, _results;
        pointerPos = scene.camera.screenToWorld('xy', e.clientX, e.clientY);
        _this.crosshair.updatePosition(pointerPos);
        _ref1 = _this.guns;
        _results = [];
        for (type in _ref1) {
          gun = _ref1[type];
          _results.push(gun.updatePosition(pointerPos));
        }
        return _results;
      });
    }

    return Stage;

  })();

}).call(this);
