// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Wall = (function(_super) {

    __extends(Wall, _super);

    function Wall(orientation) {
      var horizontal, xy, _ref;
      horizontal = orientation === 'top' || orientation === 'bottom';
      xy = [10, 220, 15];
      if (horizontal) {
        _ref = [xy[1], xy[0]], xy[0] = _ref[0], xy[1] = _ref[1];
      }
      Wall.__super__.constructor.call(this, (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(THREE.CubeGeometry, xy, function(){}), new THREE.MeshPhongMaterial({
        color: 0xaaaaaa
      }));
      this.position.z = 2.5;
      if (orientation === 'top') {
        this.position.y = 105;
      }
      if (orientation === 'right') {
        this.position.x = 105;
      }
      if (orientation === 'bottom') {
        this.position.y = -105;
      }
      if (orientation === 'left') {
        this.position.x = -105;
      }
    }

    return Wall;

  })(THREE.Mesh);

}).call(this);
