// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Enemy.Blip = (function(_super) {

    __extends(Blip, _super);

    Blip.prototype.health = 2;

    function Blip() {
      Blip.__super__.constructor.call(this, new THREE.CubeGeometry(this.size, this.size, this.size), new THREE.MeshPhongMaterial({
        color: 0xff0000
      }));
      this.rotVel = new THREE.Vector3(Math.random() - 0.5, Math.random() - 0.5, Math.random() - 0.5).multiplyScalar(5);
    }

    Blip.prototype.update = function() {
      Blip.__super__.update.apply(this, arguments);
      return this.rotation.addSelf(this.rotVel.clone().multiplyScalar(scene.stage.delta));
    };

    return Blip;

  })(Enemy);

}).call(this);
