// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Level = (function() {

    Level.levels = [];

    function Level() {
      this.spawnEnemy = __bind(this.spawnEnemy, this);
      this.winnable = false;
      this.timeouts = [];
    }

    Level.prototype.start = function() {};

    Level.prototype.spawnEnemy = function(type, pos, vel) {
      var enemy;
      enemy = new type();
      if (pos) {
        enemy.position = pos.clone();
      } else {
        enemy.position.x += (Math.random() * 2 - 1) * 30;
        enemy.position.y += (Math.random() * 2 - 1) * 30;
      }
      if (vel) {
        enemy.velocity = vel.clone();
      }
      scene.stage.enemies.push(enemy);
      scene.stage.mesh.add(enemy);
      return enemy;
    };

    Level.prototype.completed = function() {
      return this.winnable && scene.stage.enemies.length === 0;
    };

    Level.prototype.kill = function() {
      var timeout, _i, _len, _ref, _results;
      _ref = this.timeouts;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        timeout = _ref[_i];
        _results.push(clearTimeout(timeout));
      }
      return _results;
    };

    Level.prototype.after = function(seconds, fn) {
      var _this = this;
      return this.timeouts.push(setTimeout(function() {
        return fn.call(_this);
      }, seconds * 1000));
    };

    return Level;

  })();

}).call(this);
